language: perl
sudo: false

install:
  - perlbrew list
  - cpanm -n App::af
  - af missing | cpanm
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps --missing | cpanm -n

perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"

env:
  global:
    - ALIEN_BASE_NO_ABMB=1
  matrix:
    - ALIEN_FORCE=0
    - ALIEN_FORCE=1

script:
  - dzil test -v
